openapi: 3.0.0
info:
  version: 1.0.0
  title: SCMB RestAPI docs
  description: SCMB RestAPI 명세서
  license:
    name: MIT
servers:
  - url: 'http://localhost:3001/'
paths:
  /clients:
    get:
      summary: Return clients list.
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Client'
    post:
      summary: Create client.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/components/schemas/Client'
  '/clients/{id}':
    get:
      summary: Return a client.
      parameters:
        - name: id
          in: path
          description: id
          required: 'true,'
          type: integer
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/components/schemas/Client'
components:
  parameters: null
  schemas:
    Client:
      type: object
      properties:
        id:
          type: number
          description: id
        clientId:
          type: string
          description: Client's Id
        clientName:
          type: string
          description: Client's Name
        geom:
          $ref: '#/definitions/Point'
definitions:
  Geometry:
    type: object
    discriminator: type
    required:
      - type
    externalDocs:
      url: 'http://geojson.org/geojson-spec.html#geometry-objects'
    properties:
      type:
        type: string
        enum:
          - Point
          - LineString
          - Polygon
          - MultiPoint
          - MultiLineString
          - MultiPolygon
        description: the geometry type
  Point2D:
    type: array
    maxItems: 2
    minItems: 2
    items:
      type: number
  Point:
    type: object
    externalDocs:
      url: 'http://geojson.org/geojson-spec.html#id2'
    allOf:
      - $ref: '#/definitions/Geometry'
      - properties:
          coordinates:
            $ref: '#/definitions/Point2D'
